# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - np-int

pool:
  vmImage: ubuntu-latest

steps:


- task: TerraformInstaller@1
  displayName: "Install Terraform"
  inputs:
    terraformVersion: "latest"


- task: TerraformCLI@2
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'CPU-CIS-Fabric-Corp-Prod-001'
    backendAzureRmSubscriptionId: '6bae2ad5-f444-4054-bc59-73e900e89019'
    backendAzureRmResourceGroupName: 'rg-Fabric-Corp-Terraform-001'
    backendAzureRmStorageAccountName: 'stfabtfesu'
    backendAzureRmContainerName: 'azuretfstate'
    backendAzureRmKey: 'terraformpipeline.tfstate'
    allowTelemetryCollection: true"

- task: TerraformCLI@2
  inputs:
    command: 'validate'
    allowTelemetryCollection: true

- task: TerraformCLI@2
  inputs:
    command: 'apply'
    commandOptions: '-input=false'
    allowTelemetryCollection: true
