# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  bkstrgrg: 'voyager'
  bkstr: 'voyagerterraformscript01'
  bkcontainer: 'azuretfstate'
  bkstrgkey: 'terraformpipeline.tfstate'

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps: 
        - task: TerraformInstaller@1
          displayName: tfinstall
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            commandOptions: -backend=false
            backendServiceArm: 'azurepipeline'
            backendAzureRmResourceGroupName: 'voyager'
            backendAzureRmStorageAccountName: 'voyagerterraformscript01'
            backendAzureRmContainerName: 'azuretfstate'
            backendAzureRmKey: 'terraformpipeline.tfstate'
            environmentServiceNameAzureRM: 'Visual Studio Professional Subscription(8f4ad6f9-0b2b-4dda-bc17-81ebaf1478e2)'
        
        - task: TerraformTaskV4@4
          displayName: Terraform Validate
          inputs:
            provider: 'azurerm'
            command: 'validate'

  - stage: tfdeploy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps:
        - task: TerraformInstaller@1
          displayName: tfinstall
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'azurepipeline'
            backendAzureRmResourceGroupName: 'voyager'
            backendAzureRmStorageAccountName: 'voyagerterraformscript01'
            backendAzureRmContainerName: 'azuretfstate'
            backendAzureRmKey: 'terraformpipeline.tfstate'
            environmentServiceNameAzureRM: 'Visual Studio Professional Subscription(8f4ad6f9-0b2b-4dda-bc17-81ebaf1478e2)'
        - task: TerraformTaskV4@4
          displayName: Terraform Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'Visual Studio Professional Subscription(8f4ad6f9-0b2b-4dda-bc17-81ebaf1478e2)'
        - task: TerraformTaskV4@4
          displayName: Terraform Apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'Visual Studio Professional Subscription(1)(8f4ad6f9-0b2b-4dda-bc17-81ebaf1478e2)'
            